export enum Role {
  USER = 'USER',
  ARTISAN = 'ARTISAN',
  TOWN_HALL = 'TOWN_HALL',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ParticipantStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AlertType {
  WEATHER = 'WEATHER',
  CANCELLATION = 'CANCELLATION',
  SCHEDULE_CHANGE = 'SCHEDULE_CHANGE',
  GENERAL = 'GENERAL',
}

export enum AttendeeStatus {
  INTERESTED = 'INTERESTED',
  GOING = 'GOING',
  ATTENDED = 'ATTENDED',
}

export enum NotificationType {
  ALERT = 'ALERT',
  EVENT_UPDATE = 'EVENT_UPDATE',
  NEW_EVENT = 'NEW_EVENT',
  ARTISAN_UPDATE = 'ARTISAN_UPDATE',
  PARTICIPANT_APPROVED = 'PARTICIPANT_APPROVED',
  PARTICIPANT_REJECTED = 'PARTICIPANT_REJECTED',
  SYSTEM = 'SYSTEM',
}
